###

GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.cmFodWxANDU2.wxQ-KrdG952gIalzPvzyA2zPbjHM3v90JvFg1JN-lng

###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"rahul",
    "username":"rahul123",
    "password": "rahul@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"rahul123",
    "password": "rahul@456"
}