###
GET http://localhost:3000/todos/?search_q=HTML


###
GET http://localhost:3000/todos/1



###
POST http://localhost:3000/todos
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}


###
PUT http://localhost:3000/todos/10
Content-Type: application/json

{
  "status": "DONE"
}

###
DELETE http://localhost:3000/todos/1