###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}


###
GET http://localhost:3000/states
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY


###
GET http://localhost:3000/states/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY

###
GET http://localhost:3000/districts/636
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY

###
GET http://localhost:3000/states/3/stats
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY

###
DELETE http://localhost:3000/districts/765
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY


###
POST http://localhost:3000/districts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
PUT http://localhost:3000/districts/636
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA5ODAwMDE3fQ.Yepv7z95srWvbp8bVJhIcdMDHDMy10swTeTtSKa1CXY
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}